<?php use Fisharebest\Webtrees\I18N; ?>

<?= view('components/breadcrumbs', ['links' => [route('admin-control-panel') => I18N::translate('Control panel'), route('modules') => I18N::translate('Modules'), $title]]) ?>

<h1><?= $title ?></h1>

<?php
  // Save the updated preferences
  if ($action && $action === 'save') {
    echo '<div style="width: 100%; border: 2px solid #FF5E00; padding: .5rem; margin: 1rem 0 1rem; background-color: lightgoldenrodyellow;">';
    echo I18N::translate('Preferences saved');
    echo '</div>';
  }
?>

<p>
  <?= I18N::translate('On this page you can set per tree, how many years a tombstone will exist on a cemetery before it gets removed.'); ?>
  <?= I18N::translate('For Europe, a grave will last typically about 30 years, unless the family of the deceased pays for prolongation.'); ?>
</p>

<p>
  <?= /* I18N: Label for a configuration option */ I18N::translate('How many years should an individual be displayed for a missing tombstone?') ?>
</p>

<form action="<?= e(route('module', ['module' => 'webtrees-missing-tombstones', 'action' => 'Admin'])) ?>" method="post">

<?php foreach ($all_trees as $tree) : ?>
  <input
    type="number"
    name="mod_mt_years_<?= $tree->id(); ?>"
    value="<?= $tree->getPreference('mod_mt_years', $default = "30"); ?>"
    min="0" max="128" step="1"
  >
<?php endforeach ?>

<button type="submit" class="btn btn-primary">
  <?= I18N::translate('save') ?>
</button>

</form>

<?php
