language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

## Non-sudo environments are faster
sudo: false


## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - if [ -f "$HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini" ]; then cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp/; phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer install --ignore-platform-reqs --no-interaction --prefer-source
  - if [ -f "/tmp/xdebug.ini" ]; then phpenv config-add /tmp/xdebug.ini; fi

script:
  - travis_retry vendor/bin/phpunit --coverage-clover tests/clover.xml

after_script:
  - travis_retry vendor/bin/coveralls -v

